alter table STRONGHOLD_SUBJECT add constraint FK_STRONGHOLD_SUBJECT_AUTHOR foreign key (AUTHOR_ID) references SEC_USER(ID);
alter table STRONGHOLD_SUBJECT add constraint FK_STRONGHOLD_SUBJECT_TEACHER foreign key (TEACHER_ID) references SEC_USER(ID);
alter table STRONGHOLD_SUBJECT add constraint FK_STRONGHOLD_SUBJECT_MATERIALS_MAP foreign key (MATERIALS_MAP_ID) references STRONGHOLD_MATERIALS_MAP(ID);
alter table STRONGHOLD_SUBJECT add constraint FK_STRONGHOLD_SUBJECT_COURSE foreign key (COURSE_ID) references STRONGHOLD_COURSE(ID);
create unique index IDX_STRONGHOLD_SUBJECT_UK_AUTHOR_ID on STRONGHOLD_SUBJECT (AUTHOR_ID) where DELETE_TS is null ;
create index IDX_STRONGHOLD_SUBJECT_AUTHOR on STRONGHOLD_SUBJECT (AUTHOR_ID);
create index IDX_STRONGHOLD_SUBJECT_TEACHER on STRONGHOLD_SUBJECT (TEACHER_ID);
create index IDX_STRONGHOLD_SUBJECT_MATERIALS_MAP on STRONGHOLD_SUBJECT (MATERIALS_MAP_ID);
create index IDX_STRONGHOLD_SUBJECT_COURSE on STRONGHOLD_SUBJECT (COURSE_ID);
