alter table STRONGHOLD_MATERIAL_FILE_DESCRIPTOR_LINK add constraint FK_SMFDL_MATERIAL foreign key (MATERIAL_ID) references STRONGHOLD_MATERIAL(ID);
alter table STRONGHOLD_MATERIAL_FILE_DESCRIPTOR_LINK add constraint FK_SMFDL_FILE_DESCRIPTOR foreign key (FILE_DESCRIPTOR_ID) references SYS_FILE(ID);
