alter table STRONGHOLD_MATERIALS_MAP add constraint FK_STRONGHOLD_MATERIALS_MAP_MATERIAL foreign key (MATERIAL_ID) references STRONGHOLD_MATERIAL(ID);
create index IDX_STRONGHOLD_MATERIALS_MAP_MATERIAL on STRONGHOLD_MATERIALS_MAP (MATERIAL_ID);
