alter table STRONGHOLD_MATERIAL_ATTACHMENT_LINK add constraint FK_SMAL_ATTACHMENT foreign key (ATTACHMENT_ID) references STRONGHOLD_ATTACHMENT(ID);
alter table STRONGHOLD_MATERIAL_ATTACHMENT_LINK add constraint FK_SMAL_MATERIAL foreign key (MATERIAL_ID) references STRONGHOLD_MATERIAL(ID);
