alter table STRONGHOLD_ATTACHMENT add constraint FK_STRONGHOLD_ATTACHMENT_ATTACHMENT foreign key (ATTACHMENT_ID) references SYS_FILE(ID);
create index IDX_STRONGHOLD_ATTACHMENT_ATTACHMENT on STRONGHOLD_ATTACHMENT (ATTACHMENT_ID);
