alter table STRONGHOLD_ATTACHMENT add constraint FK_STRONGHOLD_ATTACHMENT_MATERIAL foreign key (MATERIAL_ID) references STRONGHOLD_MATERIAL(ID);
create index IDX_STRONGHOLD_ATTACHMENT_MATERIAL on STRONGHOLD_ATTACHMENT (MATERIAL_ID);
