alter table STRONGHOLD_ATTACHMENT_FILE_DESCRIPTOR_LINK add constraint FK_SAFDL_ATTACHMENT foreign key (ATTACHMENT_ID) references STRONGHOLD_ATTACHMENT(ID);
alter table STRONGHOLD_ATTACHMENT_FILE_DESCRIPTOR_LINK add constraint FK_SAFDL_FILE_DESCRIPTOR foreign key (FILE_DESCRIPTOR_ID) references SYS_FILE(ID);
