alter table STRONGHOLD_STUDENT add constraint FK_STRONGHOLD_STUDENT_COURSE foreign key (COURSE_ID) references STRONGHOLD_COURSE(ID);
create index IDX_STRONGHOLD_STUDENT_COURSE on STRONGHOLD_STUDENT (COURSE_ID);
