alter table STRONGHOLD_COURSE add constraint FK_STRONGHOLD_COURSE_STUDENTS foreign key (STUDENTS_ID) references STRONGHOLD_STUDENT(ID);
create index IDX_STRONGHOLD_COURSE_STUDENTS on STRONGHOLD_COURSE (STUDENTS_ID);
