alter table STRONGHOLD_SUBJECT_MATERIAL_LINK add constraint FK_SSML_MATERIAL foreign key (MATERIAL_ID) references STRONGHOLD_MATERIAL(ID);
alter table STRONGHOLD_SUBJECT_MATERIAL_LINK add constraint FK_SSML_SUBJECT foreign key (SUBJECT_ID) references STRONGHOLD_SUBJECT(ID);
