-- begin STRONGHOLD_STUDENT
alter table STRONGHOLD_STUDENT add constraint FK_STRONGHOLD_STUDENT_POSITION foreign key (POSITION_ID) references STRONGHOLD_POSITION_DIRECTORY(ID)^
alter table STRONGHOLD_STUDENT add constraint FK_STRONGHOLD_STUDENT_ORGANIZATION foreign key (ORGANIZATION_ID) references STRONGHOLD_ORGANIZATION_DIRECTORY(ID)^
alter table STRONGHOLD_STUDENT add constraint FK_STRONGHOLD_STUDENT_USER foreign key (USER_ID) references SEC_USER(ID)^
create unique index IDX_STRONGHOLD_STUDENT_UK_USER_ID on STRONGHOLD_STUDENT (USER_ID) where DELETE_TS is null ^
create index IDX_STRONGHOLD_STUDENT_POSITION on STRONGHOLD_STUDENT (POSITION_ID)^
create index IDX_STRONGHOLD_STUDENT_ORGANIZATION on STRONGHOLD_STUDENT (ORGANIZATION_ID)^
create index IDX_STRONGHOLD_STUDENT_USER on STRONGHOLD_STUDENT (USER_ID)^
-- end STRONGHOLD_STUDENT
-- begin STRONGHOLD_SUBJECT
alter table STRONGHOLD_SUBJECT add constraint FK_STRONGHOLD_SUBJECT_AUTHOR foreign key (AUTHOR_ID) references SEC_USER(ID)^
alter table STRONGHOLD_SUBJECT add constraint FK_STRONGHOLD_SUBJECT_TEACHER foreign key (TEACHER_ID) references SEC_USER(ID)^
create unique index IDX_STRONGHOLD_SUBJECT_UK_AUTHOR_ID on STRONGHOLD_SUBJECT (AUTHOR_ID) where DELETE_TS is null ^
create index IDX_STRONGHOLD_SUBJECT_AUTHOR on STRONGHOLD_SUBJECT (AUTHOR_ID)^
create index IDX_STRONGHOLD_SUBJECT_TEACHER on STRONGHOLD_SUBJECT (TEACHER_ID)^
-- end STRONGHOLD_SUBJECT

-- begin STRONGHOLD_MATERIALS_MAP
alter table STRONGHOLD_MATERIALS_MAP add constraint FK_STRONGHOLD_MATERIALS_MAP_MATERIAL foreign key (MATERIAL_ID) references STRONGHOLD_MATERIAL(ID)^
create index IDX_STRONGHOLD_MATERIALS_MAP_MATERIAL on STRONGHOLD_MATERIALS_MAP (MATERIAL_ID)^
-- end STRONGHOLD_MATERIALS_MAP

-- begin STRONGHOLD_STUDENT_PROJECT_DIRECTORY_LINK
alter table STRONGHOLD_STUDENT_PROJECT_DIRECTORY_LINK add constraint FK_SSPDL_PROJECT_DIRECTORY foreign key (PROJECT_DIRECTORY_ID) references STRONGHOLD_PROJECT_DIRECTORY(ID)^
alter table STRONGHOLD_STUDENT_PROJECT_DIRECTORY_LINK add constraint FK_SSPDL_STUDENT foreign key (STUDENT_ID) references STRONGHOLD_STUDENT(ID)^
-- end STRONGHOLD_STUDENT_PROJECT_DIRECTORY_LINK

-- begin STRONGHOLD_MATERIAL_ATTACHMENT_LINK
alter table STRONGHOLD_MATERIAL_ATTACHMENT_LINK add constraint FK_SMAL_ATTACHMENT foreign key (ATTACHMENT_ID) references STRONGHOLD_ATTACHMENT(ID)^
alter table STRONGHOLD_MATERIAL_ATTACHMENT_LINK add constraint FK_SMAL_MATERIAL foreign key (MATERIAL_ID) references STRONGHOLD_MATERIAL(ID)^
-- end STRONGHOLD_MATERIAL_ATTACHMENT_LINK
-- begin STRONGHOLD_ATTACHMENT
alter table STRONGHOLD_ATTACHMENT add constraint FK_STRONGHOLD_ATTACHMENT_ATTACHMENT foreign key (ATTACHMENT_ID) references SYS_FILE(ID)^
create index IDX_STRONGHOLD_ATTACHMENT_ATTACHMENT on STRONGHOLD_ATTACHMENT (ATTACHMENT_ID)^
-- end STRONGHOLD_ATTACHMENT

-- begin STRONGHOLD_SUBJECT_MATERIALS_MAP_LINK
alter table STRONGHOLD_SUBJECT_MATERIALS_MAP_LINK add constraint FK_SSMML_MATERIALS_MAP foreign key (MATERIALS_MAP_ID) references STRONGHOLD_MATERIALS_MAP(ID)^
alter table STRONGHOLD_SUBJECT_MATERIALS_MAP_LINK add constraint FK_SSMML_SUBJECT foreign key (SUBJECT_ID) references STRONGHOLD_SUBJECT(ID)^
-- end STRONGHOLD_SUBJECT_MATERIALS_MAP_LINK
-- begin STRONGHOLD_COURSE_STUDENT_LINK
alter table STRONGHOLD_COURSE_STUDENT_LINK add constraint FK_SCSL_COURSE foreign key (COURSE_ID) references STRONGHOLD_COURSE(ID)^
alter table STRONGHOLD_COURSE_STUDENT_LINK add constraint FK_SCSL_STUDENT foreign key (STUDENT_ID) references STRONGHOLD_STUDENT(ID)^
-- end STRONGHOLD_COURSE_STUDENT_LINK
-- begin STRONGHOLD_SUBJECT_MATERIAL_LINK
alter table STRONGHOLD_SUBJECT_MATERIAL_LINK add constraint FK_SSML_MATERIAL foreign key (MATERIAL_ID) references STRONGHOLD_MATERIAL(ID)^
alter table STRONGHOLD_SUBJECT_MATERIAL_LINK add constraint FK_SSML_SUBJECT foreign key (SUBJECT_ID) references STRONGHOLD_SUBJECT(ID)^
-- end STRONGHOLD_SUBJECT_MATERIAL_LINK
-- begin STRONGHOLD_COURSE_SUBJECT_LINK
alter table STRONGHOLD_COURSE_SUBJECT_LINK add constraint FK_SCSL_COURSE foreign key (COURSE_ID) references STRONGHOLD_COURSE(ID)^
alter table STRONGHOLD_COURSE_SUBJECT_LINK add constraint FK_SCSL_SUBJECT foreign key (SUBJECT_ID) references STRONGHOLD_SUBJECT(ID)^
-- end STRONGHOLD_COURSE_SUBJECT_LINK
