-- begin STRONGHOLD_STUDENT
alter table STRONGHOLD_STUDENT add constraint FK_STRONGHOLD_STUDENT_POSITION foreign key (POSITION_ID) references STRONGHOLD_POSITION_DIRECTORY(ID)^
alter table STRONGHOLD_STUDENT add constraint FK_STRONGHOLD_STUDENT_PROJECT foreign key (PROJECT_ID) references STRONGHOLD_PROJECT_DIRECTORY(ID)^
alter table STRONGHOLD_STUDENT add constraint FK_STRONGHOLD_STUDENT_ORGANIZATION foreign key (ORGANIZATION_ID) references STRONGHOLD_ORGANIZATION_DIRECTORY(ID)^
alter table STRONGHOLD_STUDENT add constraint FK_STRONGHOLD_STUDENT_USER foreign key (USER_ID) references SEC_USER(ID)^
create unique index IDX_STRONGHOLD_STUDENT_UK_USER_ID on STRONGHOLD_STUDENT (USER_ID) where DELETE_TS is null ^
create index IDX_STRONGHOLD_STUDENT_POSITION on STRONGHOLD_STUDENT (POSITION_ID)^
create index IDX_STRONGHOLD_STUDENT_PROJECT on STRONGHOLD_STUDENT (PROJECT_ID)^
create index IDX_STRONGHOLD_STUDENT_ORGANIZATION on STRONGHOLD_STUDENT (ORGANIZATION_ID)^
create index IDX_STRONGHOLD_STUDENT_USER on STRONGHOLD_STUDENT (USER_ID)^
-- end STRONGHOLD_STUDENT
-- begin STRONGHOLD_SUBJECT
alter table STRONGHOLD_SUBJECT add constraint FK_STRONGHOLD_SUBJECT_AUTHOR foreign key (AUTHOR_ID) references SEC_USER(ID)^
alter table STRONGHOLD_SUBJECT add constraint FK_STRONGHOLD_SUBJECT_TEACHER foreign key (TEACHER_ID) references SEC_USER(ID)^
alter table STRONGHOLD_SUBJECT add constraint FK_STRONGHOLD_SUBJECT_MATERIALS_MAP foreign key (MATERIALS_MAP_ID) references STRONGHOLD_MATERIALS_MAP(ID)^
alter table STRONGHOLD_SUBJECT add constraint FK_STRONGHOLD_SUBJECT_COURSE foreign key (COURSE_ID) references STRONGHOLD_COURSE(ID)^
create unique index IDX_STRONGHOLD_SUBJECT_UK_AUTHOR_ID on STRONGHOLD_SUBJECT (AUTHOR_ID) where DELETE_TS is null ^
create index IDX_STRONGHOLD_SUBJECT_AUTHOR on STRONGHOLD_SUBJECT (AUTHOR_ID)^
create index IDX_STRONGHOLD_SUBJECT_TEACHER on STRONGHOLD_SUBJECT (TEACHER_ID)^
create index IDX_STRONGHOLD_SUBJECT_MATERIALS_MAP on STRONGHOLD_SUBJECT (MATERIALS_MAP_ID)^
create index IDX_STRONGHOLD_SUBJECT_COURSE on STRONGHOLD_SUBJECT (COURSE_ID)^
-- end STRONGHOLD_SUBJECT
-- begin STRONGHOLD_COURSE
alter table STRONGHOLD_COURSE add constraint FK_STRONGHOLD_COURSE_SUBJECT foreign key (SUBJECT_ID) references STRONGHOLD_SUBJECT(ID)^
alter table STRONGHOLD_COURSE add constraint FK_STRONGHOLD_COURSE_STUDENTS foreign key (STUDENTS_ID) references STRONGHOLD_STUDENT(ID)^
create index IDX_STRONGHOLD_COURSE_SUBJECT on STRONGHOLD_COURSE (SUBJECT_ID)^
create index IDX_STRONGHOLD_COURSE_STUDENTS on STRONGHOLD_COURSE (STUDENTS_ID)^
-- end STRONGHOLD_COURSE
-- begin STRONGHOLD_MATERIALS_MAP
alter table STRONGHOLD_MATERIALS_MAP add constraint FK_STRONGHOLD_MATERIALS_MAP_MATERIAL foreign key (MATERIAL_ID) references STRONGHOLD_MATERIAL(ID)^
create index IDX_STRONGHOLD_MATERIALS_MAP_MATERIAL on STRONGHOLD_MATERIALS_MAP (MATERIAL_ID)^
-- end STRONGHOLD_MATERIALS_MAP
-- begin STRONGHOLD_MATERIAL
alter table STRONGHOLD_MATERIAL add constraint FK_STRONGHOLD_MATERIAL_ATTACHMENT foreign key (ATTACHMENT_ID) references SYS_FILE(ID)^
create index IDX_STRONGHOLD_MATERIAL_ATTACHMENT on STRONGHOLD_MATERIAL (ATTACHMENT_ID)^
-- end STRONGHOLD_MATERIAL
